#!/bin/bash

# Yabai SRE Zen Config
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Aesthetics
yabai -m config window_shadow on
yabai -m config window_border off
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.85

# Behavior
yabai -m config focus_follows_mouse autoresize
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Signal rules
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

echo "yabai configuration loaded.."
