[general]
import = []

[window]
padding = { x = 15, y = 15 }
opacity = 0.9
decorations = "None"
class = { instance = "Alacritty", general = "Alacritty" }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 14.0

[colors.primary]
background = "#011628"
foreground = "#CBE0F0"

[colors.cursor]
text = "#011628"
cursor = "#CBE0F0"

[colors.normal]
black   = "#011628"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#CBE0F0"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#ffffff"

[colors.selection]
background = "#143652"
foreground = "#CBE0F0"
